commonLabels:
  app: cdci-demo-app

bases:
- ../../base

namespace: my-namespace-prod

patchesStrategicMerge:
- replicas.yaml

secretGenerator:
- name: cicd-demo-app-secrets
  envs:
  - secrets.env
  files:
  - secrets.json