apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: cicd-demo-app-container
        image: matdurand/cicd-demo-app:1.1.1-master-latest
        imagePullPolicy: Always
        volumeMounts:
        - name: cicd-demo-app-secrets-volume
          mountPath: "/var/secrets"
          readOnly: true
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: cicd-demo-app-configmap
        env:
        - name: SECRET_CARAMILK
          valueFrom:
            secretKeyRef:
              name: cicd-demo-app-secrets
              key: caramilk_secret
      volumes:
      - name: cicd-demo-app-secrets-volume
        secret:
          secretName: cicd-demo-app-secrets